### ISSUE TITLE
about the feature

### ISSUE THREAD

**Issue by 96091165** [ybendou/easy#12]
Hello, I have a question about the feature.

Why do the inductive and transductive use the same feature?

I thought they were using different ways to train cause the testing set had only been used in transductive learning, not inductive learning.

Thanks.

**Comment by ybendou** [comment]
Hello, 

The training of the backbone is the same for the inductive and transductive settings, it's the same backbone for both.
The difference is when doing few-shot evaluation, where in transductive the other queries features are taken into account without their labels. In the inductive setting we only have access to each query individually without any knowledge on the other queries. You can refer to the paper for more details or the code ( [inductive](https://github.com/ybendou/easy/blob/main/few_shot_eval.py#L31) and [transductive](https://github.com/ybendou/easy/blob/main/few_shot_eval.py#L100) ).
The testing set has both inductive and transductive options. Please refer to the README. 

For inductive EASY : 

`$ python main.py --dataset-path "<dataset-path>" --dataset miniimagenet --model resnet12 --test-features "[<path>/minifeaturesAS1.pt11, <path>/minifeaturesAS2.pt11, <path>/minifeaturesAS3.pt11]" --preprocessing ME --n-shots 1`

For transductive EASY : 

`$ python main.py --dataset-path "<dataset-path>" --dataset miniimagenet --model resnet12 --test-features "[<path>/minifeaturesAS1.pt11, <path>/minifeaturesAS2.pt11, <path>/minifeaturesAS3.pt11]" --postrocessing ME  --transductive --transductive-softkmeans --transductive-temperature-softkmeans 5 --n-shots 1`

**Comment by 96091165** [comment]
I got it, thank you very much.
