### ISSUE TITLE
Training on tieredImageNet leads to CUDA out of memory.

### ISSUE THREAD

**Issue by whyygug** [ybendou/easy#13]
Hello, 

In this issue https://github.com/ybendou/easy/issues/11#issuecomment-1116237889 you mentioned changing the argument `dataset` to `‘tieredimagenet’`  can reproduce the results on tieredImageNet.  
My device is an RTX 3090 with 24GB memory. Even if I reduce the batch size from 128 to 64, there is still the problem of out of GPU memory during training. 
I noticed that the memory usage is only about 6GB during training, but once the training of a epoch is finished and the validation starts, the GPU memory is immediately exhausted.
What should I do to complete the training on tieredImageNet?

Best,

**Comment by whyygug** [comment]
After I change `batch-fs` to 10, the problem of out of CUDA memory is solved, but now the training is too slow where most of the time is spent on validation, one epoch takes 30 minutes to complete. If I need to get the results of the validation to plot the loss curve, then I can't use the `--skip_epochs` to skip the validation. Is there any way to speed up the validation?

**Comment by ybendou** [comment]
Hello, 

Unfortunately it is the speed limit of the gpu. You can increase bach-fs but you will be limited with the memory of the gpu.
We have tried to parallelise the validation process to make it as fast as possible. But tiered dataset is very large and takes much time. 
I recommend you to use skip epochs up till the last 50 epochs. 

Best,

**Comment by whyygug** [comment]
Thank you for your reply, I will try some ways to improve the speed of validation in the future.
