### ISSUE TITLE
Reproduce the outcome of 2x_ResNet12_√2

### ISSUE THREAD

**Issue by LIUZIJING-CHN** [ybendou/easy#15]
First of all, thx for your work!
Since I want to reproduce the outcome of 2x_ResNet12_√2 which has an accuracy of 70 in 1-shot case on mini-ImageNet, I want to know what is the training setting of the **main.py**? I want to extract the features from my own-trained model, hope you can help me.

**Comment by ybendou** [comment]
Hello, 
To do so, you will need to generate two sets of features (one for each ResNet12_√2)
You can use the following 2 commands to get 2 features : 
```
python main.py --dataset-path <dataset-path> --dataset <dataset_name> --model resnet12 --feature-maps 45 --epochs 0  --batch-size 128 --n-shots 1  --load-model <your_model_path> --save-features <path_to_features1> --sample-aug 20
```

```
python main.py --dataset-path <dataset-path> --dataset <dataset_name> --model resnet12 --feature-maps 45 --epochs 0  --batch-size 128 --n-shots 1  --load-model <your_model_path> --save-features <path_to_features2> --sample-aug 20
```

Then finally you can test your results as follows:

```
python main.py --dataset-path "<dataset-path>" --dataset <dataset_name> --model resnet12 --test-features "[<path_to_features1>, <path_to_features2>]" --preprocessing ME --n-shots 1
```

Sorry for the delayed answer, I hope this helps.
Let me know if it doesn't work.

Best,

**Comment by LIUZIJING-CHN** [comment]
I see. Thx for your reply!!
