### ISSUE TITLE
Argument setting for training other datasets

### ISSUE THREAD

**Issue by LIUZIJING-CHN** [ybendou/easy#18]
Sorry to bother again. I wonder if you can provide the argument setting for reproducing outcomes of the other datasets like CIFAR-FS or Tiered-ImageNet. Hope this won't bring you much trouble. Thx a lot.

**Comment by ybendou** [comment]
Hello, 

For tiered you can use the following command: 

```python main.py --dataset tieredimagenet --model resnet12 --milestones 300 --epochs 0 --manifold-mixup 1500 --cosine --gamma 0.9 --rotations --batch-size 128 --device cuda:0 --preprocessing ""ME"" --dataset-size 12800  --skip-epochs 1450 --deterministic```

For cifarfs:

```python main.py --dataset cifarfs --model resnet12 --milestones 300 --epochs 0 --manifold-mixup 1500 --cosine --gamma 0.9 --rotations --batch-size 128 --device cuda:0 --preprocessing ""ME"" --dataset-size 12800  --skip-epochs 1450 --deterministic```

You also need to add the path of your datasets folder --dataset-path 

Let me know if i doesn't work. 

Brest, 
Yassir

**Comment by LIUZIJING-CHN** [comment]
> 

Thx for such a quick reply! I'll try them soon.

**Comment by LIUZIJING-CHN** [comment]
> 

By the way, the argument for CIFAR-FS may be wrong. I wonder if you directly copy that for tiered-ImageNet?

**Comment by ybendou** [comment]
Sorry for the typo, I modified it. Indeed, it's the same parameters for both datasets, the only difference is --dataset cifarfs instead.

**Comment by LIUZIJING-CHN** [comment]
sorry to bother again, but what about CUB and FC-100? I am not meant to bother you,  my project depends on your code, and I need a full reproduction. Sorry again

**Comment by ybendou** [comment]
Hello, 

No worries, regarding the data choices, it's using the --dataset parameter and these are all the possible options: 
['miniimagenet', 'cubfs','tieredimagenet', 'fc100', 'cifarfs'].  So for CUB it's cubfs and FC-100 it's fc100.

Hope this helps, 

Best,

**Comment by LIUZIJING-CHN** [comment]
I mean the important arguments like dataset-size & manifold epoch, are they the same as that of mini-imagenet or tieredimagenet?

**Comment by ybendou** [comment]
Hello,

Sorry for the late answer, I double checked and the right parameters for cubfs, fc100 and cifarfs100 datasets should be the following: 
--manifold-mixup 600 --milestones 100 --skip-epochs 550 
without the --dataset-size option:
```python main.py --dataset cifarfs --model resnet12 --milestones 100 --epochs 0 --manifold-mixup 600 --cosine --gamma 0.9 --rotations --batch-size 128 --device cuda:0 --preprocessing ""ME"" --skip-epochs 550 --deterministic
```
Only miniimagenet and tieredimagenet are trained for 1500 epochs with the dataset-size option.

**Comment by LIUZIJING-CHN** [comment]
I see，THX again！
