### ISSUE TITLE
running the experiment

### ISSUE THREAD

**Issue by shepherdls** [ybendou/easy#20]
When running the experiment, how to enter the 3 feature file paths。
--test-features "[<path>/minifeatures1.pt11, <path>/minifeatures2.pt11, <path>/minifeatures3.pt11]"
when input   
-test-features "[~/lishuai/hhh/minifeatures1.pt11, ~/lishuai/hhh/minifeatures2.pt11, ~/lishuai/hhh/minifeatures3.pt11]"
alway output  
FileNotFoundError: [Errno 2] No such file or directory: '[~/lishuai/hhh/minifeatures1.pt11, ~/lishuai/hhh/minifeatures2.pt11, ~/lishuai/hhh/minifeatures3.pt11]'
what's wrong? how to resolve?

**Comment by shepherdls** [comment]
could sb help me? please!

**Comment by ybendou** [comment]
Hi, 

Can you try the following? 
--test-features "['~/lishuai/hhh/minifeatures1.pt11', '~/lishuai/hhh/minifeatures2.pt11', '/lishuai/hhh/minifeatures3.pt11']"

Let me know if it doens't work
Best,

**Comment by shepherdls** [comment]
outut
FileNotFoundError: [Errno 2] No such file or directory: '/lishuai/hhh/minifeatures1.pt11'
but i have this file.

**Comment by ybendou** [comment]
can you try with just on feature? maybe the path name is not correct. 

Does --test-features '/lishuai/hhh/minifeatures1.pt11' work?
Best,

**Comment by shepherdls** [comment]
just one feature can work, only three features' path  can not work

**Comment by shepherdls** [comment]
when input
--test-features ~/lishuai/hhh/minifeatures1.pt11
can work

**Comment by ybendou** [comment]
what about: ```--test-features "[' ~/lishuai/hhh/minifeatures1.pt11', '~/lishuai/hhh/minifeatures2.pt11', '~ /lishuai/hhh/minifeatures3.pt11']"```?
I think what is missing is the root symbol (``` ~ ```)

**Comment by shepherdls** [comment]
inpput 
--test-features "[' ~/lishuai/hhh/minifeatures1.pt11', '~/lishuai/hhh/minifeatures2.pt11', '~ /lishuai/hhh/minifeatures3.pt11']"
output 
FileNotFoundError: [Errno 2] No such file or directory: '~/lishuai/hhh/minifeatures1.pt11'

**Comment by shepherdls** [comment]
thank you for your reply


when input one feature can work








when input three features can not work









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ybendou/easy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ybendou/easy] running the experiment (Issue #20)





 
what about: --test-features "['/lishuai/hhh/minifeatures1.pt11', '/lishuai/hhh/minifeatures2.pt11', '/lishuai/hhh/minifeatures3.pt11']" ?
 I think what is missing is the root symbol ()

**Comment by shepherdls** [comment]
Doctor ybendou:
&nbsp; hello,&nbsp;I haven't found a solution to the last problem, so I would like to consult you again.
&nbsp; I tried again if the code works when I input one feature file and three feature files.
&nbsp; Firstly,&nbsp;My feature&nbsp;file path is correct, when a feature&nbsp;file is entered, the code runs and can verify this.
&nbsp; when input one feature can works.








&nbsp;when input three features can not work,&nbsp;I tried various input forms of the three features, but none of the codes worked, and the results are as follows:


form 1


form 2



form 3



form 4



form 5



I've tried everything I can think of to no avail, if you have a solution please let me know, I'd be very grateful!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;lishuai
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;2023年1月27日



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ybendou/easy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ybendou/easy] running the experiment (Issue #20)





 
what about: --test-features "['/lishuai/hhh/minifeatures1.pt11', '/lishuai/hhh/minifeatures2.pt11', '/lishuai/hhh/minifeatures3.pt11']" ?
 I think what is missing is the root symbol ()

**Comment by ybendou** [comment]
Hello,  
Can you share a screenshot of your terminal? 
I am not able to reproduce your bug. 
The following command works for me: 
```python main.py --test-features "['/hdd/data/features/easyfeatures/cifarfeatures1.pt11', '/hdd/data/features/easyfeatures/cifarfeatures2.pt11', '/hdd/data/features/easyfeatures/cifarfeatures2.pt11']" --dataset-path ~/Documents/datasets --dataset cifarfs```

<img width="1419" alt="Screenshot 2023-02-06 at 12 37 36" src="https://user-images.githubusercontent.com/38562509/216961832-4017eed7-fea9-40d9-a7f8-82f82616f116.png">

**Comment by shepherdls** [comment]
Hello,
&nbsp; thank you for your reply!
&nbsp; If it is convenient, you can check the reply in the mailbox, because I am afraid that the screenshot on GitHub will not be displayed, and it was not displayed in the last email to you.&nbsp;
&nbsp;&nbsp;My input refers to the format you gave on GitHub, as shown in the red circle in the figure below:

&nbsp;&nbsp;The content in the red circle is as follows：
&nbsp;&nbsp;$ python main.py --dataset-path "<dataset-path&gt;" --dataset miniimagenet --model resnet12 --test-features "['<path&gt;/minifeatures1.pt11', '<path&gt;/minifeatures2.pt11', '<path&gt;/minifeatures3.pt11']" --preprocessing ME --n-shots 1
&nbsp;
&nbsp; The following is a screenshot of my terminal input：

&nbsp; but i have this file,&nbsp;As shown in the figure below:
&nbsp;&nbsp;



&nbsp; when i input one feature, it can work, As shown in the figure below:



&nbsp;When I refer to the input format in your email just now, it can not work.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ybendou/easy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月6日(星期一) 晚上7:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ybendou/easy] running the experiment (Issue #20)





 
Hello,
 Can you share a screenshot of your terminal?
 I am not able to reproduce your bug.
 The following command works for me:
 python main.py --test-features "['/hdd/data/features/easyfeatures/cifarfeatures1.pt11', '/hdd/data/features/easyfeatures/cifarfeatures2.pt11', '/hdd/data/features/easyfeatures/cifarfeatures2.pt11']" --dataset-path ~/Documents/datasets --dataset cifarfs

**Comment by ybendou** [comment]
Hello, 

Could you share the screenshot via mail? yassir.bendou@gmail.com
I am not able to read the screenshot even in the reply in the mailbox. 

Best,
