### ISSUE TITLE
Other backbones

### ISSUE THREAD

**Issue by Qianshaowei** [ybendou/easy#5]
Thanks for your work.
Do you have the weight files of other backbone networks that you have trained? Such as WideResNet28 and ResNet10.

**Comment by ybendou** [comment]
Hello, 

We only train for ResNet12 in the paper. However, the code is ready for WideResNet28 and you can use it to train a WRN-28 by setting  `--model 'wideresnet'` in the training command.

Hope this helps,

Best,

**Comment by Qianshaowei** [comment]
> 

Ok, I know this command, but it takes too much time to train a pretrained model. 
Thanks for your reply.

**Comment by shepherdls** [comment]
hello, i have a question.
for the wideresnet28 and fc100, the following command can be ok?
python main.py  --dataset-path /home/dataset  --dataset FC100  --model  wideresnet   --milestones 100   --epochs 0   --manifold-mixup 600   --cosine   --gamma  0.9   --rotation   --batch-size 64   --device cuda: 0   --preprocessing  ME   --skip-epochs 550 --save-model /home/1.pt1 --n-shots 5
what's the setting of --epochs, manifold-mixup and  --skip-epochs ,the values are  right?
