### ISSUE TITLE
how do you put your dataset?

### ISSUE THREAD

**Issue by czczmr** [ybendou/easy#7]
can you give a picture about your dataset form？

**Comment by ybendou** [comment]
Hello, 
I'm not sure I understand your question. Could you elaborate more? 
If it's regarding how the dataset is created, all the used dataset are publicly available for few-shot learning benchmarking.
miniImageNet and tieredImagenet are subsets of ImageNet.

If your question is about how the dataset and the loader are created in the code, we use the same dataset object (CPUDataset) but with different inputs depending on each dataset (miniImagenet, cubfs, cifarfs...) : https://github.com/ybendou/easy/blob/main/datasets.py#L8

Hope this answers your question, 
Best,
