### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by RongKaiWeskerMA** [ybendou/easy#8]
Hi author

Thanks for open sourcing your work! I am just curious about how the data augmentation is performed during validation and testing? I couldn't find the code performing 30 times cropping in the dataset.py

**Comment by ybendou** [comment]
Hello, 

Thanks, I'm glad you enjoy our work.
Regarding the cropping, it is done in the dataset.py file when args.sample_aug >1.
For example, for miniImageNet, it's in line 332:  https://github.com/ybendou/easy/blob/main/datasets.py#L332

Hope this helps, 
Best,
